@echo off
call "C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Auxiliary/Build/vcvars64.bat"

setlocal enabledelayedexpansion
set WORKSPACE=%~dp0/..
set FBXSDK_ROOT=%WORKSPACE%/FBXSDK
set SBSARSDK_ROOT=%WORKSPACE%/SBSARSDK
set DRACO_ROOT=%WORKSPACE%/draco
set USD_BUILD_PATH=%WORKSPACE%/usd_build
set FILEFORMAT_ROOT=%WORKSPACE%/USD-Fileformat-plugins
set PATH=%USD_BUILD_PATH%/bin;%USD_BUILD_PATH%/lib;%PATH%

set CMAKE_ARGS=
set CMAKE_ARGS=%CMAKE_ARGS% -S %FILEFORMAT_ROOT% -B %WORKSPACE%/fileformat_build -G "Visual Studio 17 2022" -A x64
set CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_INSTALL_PREFIX=%WORKSPACE%/fileformat_install
set CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_BUILD_TYPE=Release
set CMAKE_ARGS=%CMAKE_ARGS% -Dpxr_ROOT=%USD_BUILD_PATH%
set CMAKE_ARGS=%CMAKE_ARGS% -DFBXSDK_ROOT=%FBXSDK_ROOT%
set CMAKE_ARGS=%CMAKE_ARGS% -Dsubstance_DIR=%SBSARSDK_ROOT%
set CMAKE_ARGS=%CMAKE_ARGS% -Ddraco_ROOT=%DRACO_ROOT%
set CMAKE_ARGS=%CMAKE_ARGS% -DOpenImageIO_DIR=%USD_BUILD_PATH%/lib/cmake/OpenImageIO
set CMAKE_ARGS=%CMAKE_ARGS% -DUSD_FILEFORMATS_BUILD_TESTS=ON
set CMAKE_ARGS=%CMAKE_ARGS% -DUSD_FILEFORMATS_ENABLE_FBX=ON
set CMAKE_ARGS=%CMAKE_ARGS% -DUSD_FILEFORMATS_ENABLE_GLTF=ON
set CMAKE_ARGS=%CMAKE_ARGS% -DUSD_FILEFORMATS_ENABLE_OBJ=ON
set CMAKE_ARGS=%CMAKE_ARGS% -DUSD_FILEFORMATS_ENABLE_PLY=ON
set CMAKE_ARGS=%CMAKE_ARGS% -DUSD_FILEFORMATS_ENABLE_SPZ=ON
set CMAKE_ARGS=%CMAKE_ARGS% -DUSD_FILEFORMATS_ENABLE_STL=ON
set CMAKE_ARGS=%CMAKE_ARGS% -DUSD_FILEFORMATS_ENABLE_SBSAR=ON
set CMAKE_ARGS=%CMAKE_ARGS% -DUSD_FILEFORMATS_ENABLE_DRACO=ON
cmake %CMAKE_ARGS%

cmake --build %WORKSPACE%/fileformat_build --config Release
cmake --install %WORKSPACE%/fileformat_build --config Release